name: xxo25
description: "Bug WhatsApp Crasher"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^0.13.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Device & permissions
  device_info_plus: ^9.1.2
  permission_handler: ^11.3.1
  network_info_plus: ^5.0.0

  # Media
  image_picker: ^1.1.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  audioplayers: ^6.1.0
  share_plus: ^10.0.3
  path_provider: ^2.1.5

  # UI
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1

  # Network
  web_socket_channel: ^3.0.1

  # Files & web
  file_picker: ^8.1.7
  path: ^1.9.1
  webview_flutter: ^4.10.0

  # Other
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon.jpg
  image_path_ios: assets/icon/icon/icon.jpg
  image_path: assets/icon/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/reze.png
    - assets/videos/landing.mp4
    - assets/videos/splash.mp4
    - assets/videos/banner.mp4
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
    - family: ShareTechMono
      fonts:
        - asset: fonts/ShareTechMono-Regular.ttf
